### ISSUE TITLE
Is it possible to include every file in the portable folder?

### ISSUE THREAD

**Issue by luixxiul** [crazy-max/brave-portable#1]
Instead of the renaming folder which has been existed.

I'm bit confused that all information was copied from the existing profile, wondering if the data is actually inside the newly created folder for the portable browser.

**Comment by crazy-max** [comment]
Yes, indeed, all the files (profiles, extensions, etc ...) are in the "data" folder.
Data folder is not duplicated, only moved! Then, the old folder (`%APPDATA%\brave`) is deleted and a symbolic link is created, pointing your portable folder.

**Comment by luixxiul** [comment]
Thanks for explanation. If so, would you please provide an option to disable to copy the existing profile and install the browser afresh?

**Comment by crazy-max** [comment]
You can do that by closing the browser rename `data` to `data_old` for example and launch `brave-portable.exe` again.

**Comment by luixxiul** [comment]
OK I see, let me try.
