### ISSUE TITLE
Avast & AVG - Win32:Malware-gen

### ISSUE THREAD

**Issue by AdKiller** [crazy-max/brave-portable#2]
brave-portable-x64-0.18.14-7-setup.exe

https://www.virustotal.com/#/file/7d1cf6967371e02f1e0ae6856e52ec842330f15ab679f175412afdc4f60de8fe/detection

less worrisome: 

brave-portable-x64-0.18.14-7.7z

Jiangmin - TrojanDropper.Dapato.yae

https://www.virustotal.com/#/file/e7f2ef64482b8c2702a52d5066db1da585bf5285b2af53abc6a3c2de536cdb3c/detection

What is going on?

**Comment by crazy-max** [comment]
Hi,

The detected executable by VirusTotal is `brave-portable.exe` (ia32 and x64).
Win32:Malware-gen and others found by the VirusTotal scan are generic.
Most likely based on a heuristic detection. Heuristics are more prone to false-positive detections.
You can have more info here : https://malwaretips.com/blogs/win32evo-gen-susp-virus/

I will make a new release of the portable executable.

Thanks for your contrib

**Comment by crazy-max** [comment]
Check the latest release
