### ISSUE TITLE
I have brave portable installed. How do I update the browser?

### ISSUE THREAD

**Issue by codename-littleboy** [crazy-max/brave-portable#3]
Would installing it in the install folder keep previous data? Or will it be erased?

**Comment by crazy-max** [comment]
Hi @codename-littleboy,

You can safely update using the latest setup called `brave-portable-{ia32,x64}-x.x.x-x-setup.exe`. But in case something goes wrong, make a backup ;)

**Comment by codename-littleboy** [comment]
Thanks for the nice reply. I would like to introduce you to a platform that rewards open source contributors with steem. Steem is like shares that have a value and can be exchanged for dollars. You can raise money for your contributions by writing about it (20$-40$) per release. The site is Utopian.io . If you are interested let me know. I will help you with the rules if you help me with how to make portable app. I want to make some apps portable. But I am a complete novice about coding.

I love the idea behind brave. I would like to make documetation posts about how to use the browser as well.
